/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as EventContractJson } from "../Event.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace EventTypes {
  export type Fields = {
    predictTemplateId: HexString;
    punterTemplateId: HexString;
    roundTemplateId: HexString;
    operator: Address;
    feesBasisPts: bigint;
    repeatEvery: bigint;
    claimedByAnyoneDelay: bigint;
    eventCounter: bigint;
  };

  export type State = ContractState<Fields>;

  export type BetBullEvent = ContractEvent<{
    from: Address;
    epoch: bigint;
    amount: bigint;
    up: boolean;
  }>;
  export type BetBearEvent = ContractEvent<{
    from: Address;
    epoch: bigint;
    amount: bigint;
    up: boolean;
  }>;
  export type RoundEndedEvent = ContractEvent<{ epoch: bigint; price: bigint }>;
  export type RoundStartedEvent = ContractEvent<{
    epoch: bigint;
    price: bigint;
  }>;
  export type ClaimedEvent = ContractEvent<{
    addressToClaim: Address;
    from: Address;
    epochs: HexString;
  }>;
  export type EventCreatedEvent = ContractEvent<{
    contractId: HexString;
    eventId: bigint;
  }>;
}

class Factory extends ContractFactory<EventInstance, EventTypes.Fields> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as EventTypes.Fields;
  }

  eventIndex = {
    BetBull: 0,
    BetBear: 1,
    RoundEnded: 2,
    RoundStarted: 3,
    Claimed: 4,
    EventCreated: 5,
  };
  consts = {
    ErrorCodes: {
      InvalidCaller: BigInt(300),
      EventNotExists: BigInt(301),
      EventAlreadyExists: BigInt(302),
    },
    SubContractTypes: { Event: "03" },
  };

  at(address: string): EventInstance {
    return new EventInstance(address);
  }

  tests = {
    getEvent: async (
      params: TestContractParams<EventTypes.Fields, { eventId: bigint }>
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getEvent", params);
    },
    createEvent: async (
      params: Omit<TestContractParams<EventTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "createEvent", params);
    },
    destroyPredict: async (
      params: TestContractParams<EventTypes.Fields, { eventId: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroyPredict", params);
    },
    startRound: async (
      params: TestContractParams<
        EventTypes.Fields,
        { eventId: bigint; from: Address; price: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "startRound", params);
    },
    endRound: async (
      params: TestContractParams<
        EventTypes.Fields,
        { eventId: bigint; actualPrice: bigint; immediatelyStart: boolean }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "endRound", params);
    },
    bid: async (
      params: TestContractParams<
        EventTypes.Fields,
        { eventId: bigint; amount: bigint; up: boolean }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "bid", params);
    },
    withdraw: async (
      params: TestContractParams<
        EventTypes.Fields,
        { eventId: bigint; arrayEpochIn: HexString; addressToClaim: Address }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdraw", params);
    },
    setNewRepeatEvery: async (
      params: TestContractParams<EventTypes.Fields, { newRecurrence: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setNewRepeatEvery", params);
    },
    setNewFees: async (
      params: TestContractParams<EventTypes.Fields, { basisPts: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setNewFees", params);
    },
    setNewOperator: async (
      params: TestContractParams<EventTypes.Fields, { newOperator: Address }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setNewOperator", params);
    },
    setNewClaimedByAnyone: async (
      params: TestContractParams<
        EventTypes.Fields,
        { newClaimedByAnyoneDelay: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setNewClaimedByAnyone", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Event = new Factory(
  Contract.fromJson(
    EventContractJson,
    "",
    "53f62dc5561d77b20f764374d9093db92d4a009fa0a6f8868968fbce41e67719"
  )
);

// Use this class to interact with the blockchain
export class EventInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<EventTypes.State> {
    return fetchContractState(Event, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeBetBullEvent(
    options: EventSubscribeOptions<EventTypes.BetBullEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Event.contract,
      this,
      options,
      "BetBull",
      fromCount
    );
  }

  subscribeBetBearEvent(
    options: EventSubscribeOptions<EventTypes.BetBearEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Event.contract,
      this,
      options,
      "BetBear",
      fromCount
    );
  }

  subscribeRoundEndedEvent(
    options: EventSubscribeOptions<EventTypes.RoundEndedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Event.contract,
      this,
      options,
      "RoundEnded",
      fromCount
    );
  }

  subscribeRoundStartedEvent(
    options: EventSubscribeOptions<EventTypes.RoundStartedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Event.contract,
      this,
      options,
      "RoundStarted",
      fromCount
    );
  }

  subscribeClaimedEvent(
    options: EventSubscribeOptions<EventTypes.ClaimedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Event.contract,
      this,
      options,
      "Claimed",
      fromCount
    );
  }

  subscribeEventCreatedEvent(
    options: EventSubscribeOptions<EventTypes.EventCreatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Event.contract,
      this,
      options,
      "EventCreated",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | EventTypes.BetBullEvent
      | EventTypes.BetBearEvent
      | EventTypes.RoundEndedEvent
      | EventTypes.RoundStartedEvent
      | EventTypes.ClaimedEvent
      | EventTypes.EventCreatedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(Event.contract, this, options, fromCount);
  }
}
