/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as BidScriptJson } from "../Bid.ral.json";
import { default as BoostRoundScriptJson } from "../BoostRound.ral.json";
import { default as CreateGameScriptJson } from "../CreateGame.ral.json";
import { default as DestroyRoundScriptJson } from "../DestroyRound.ral.json";
import { default as EndScriptJson } from "../End.ral.json";
import { default as GameBidScriptJson } from "../GameBid.ral.json";
import { default as GameBoostScriptJson } from "../GameBoost.ral.json";
import { default as GameDestroyPredictionScriptJson } from "../GameDestroyPrediction.ral.json";
import { default as GameDestroyRoundScriptJson } from "../GameDestroyRound.ral.json";
import { default as GameEndScriptJson } from "../GameEnd.ral.json";
import { default as GameStartScriptJson } from "../GameStart.ral.json";
import { default as GameWithdrawScriptJson } from "../GameWithdraw.ral.json";
import { default as NewIntervalScriptJson } from "../NewInterval.ral.json";
import { default as NewOperatorScriptJson } from "../NewOperator.ral.json";
import { default as StartScriptJson } from "../Start.ral.json";
import { default as WithdrawScriptJson } from "../Withdraw.ral.json";

export const Bid = new ExecutableScript<{
  predict: HexString;
  amount: bigint;
  up: boolean;
}>(Script.fromJson(BidScriptJson));
export const BoostRound = new ExecutableScript<{
  predict: HexString;
  amount: bigint;
  epochToBoost: bigint;
}>(Script.fromJson(BoostRoundScriptJson));
export const CreateGame = new ExecutableScript<{
  game: HexString;
  feesBasisPts: bigint;
  repeatEvery: bigint;
  claimedByAnyoneDelay: bigint;
}>(Script.fromJson(CreateGameScriptJson));
export const DestroyRound = new ExecutableScript<{
  predict: HexString;
  arrayEpoch: HexString;
}>(Script.fromJson(DestroyRoundScriptJson));
export const End = new ExecutableScript<{
  predict: HexString;
  price: bigint;
  immediatelyStart: boolean;
}>(Script.fromJson(EndScriptJson));
export const GameBid = new ExecutableScript<{
  game: HexString;
  gameId: bigint;
  amount: bigint;
  up: boolean;
}>(Script.fromJson(GameBidScriptJson));
export const GameBoost = new ExecutableScript<{
  game: HexString;
  gameId: bigint;
  amount: bigint;
  epochToBoost: bigint;
}>(Script.fromJson(GameBoostScriptJson));
export const GameDestroyPrediction = new ExecutableScript<{
  game: HexString;
  gameId: bigint;
}>(Script.fromJson(GameDestroyPredictionScriptJson));
export const GameDestroyRound = new ExecutableScript<{
  game: HexString;
  gameId: bigint;
  arrayEpoch: HexString;
}>(Script.fromJson(GameDestroyRoundScriptJson));
export const GameEnd = new ExecutableScript<{
  game: HexString;
  gameId: bigint;
  price: bigint;
  immediatelyStart: boolean;
}>(Script.fromJson(GameEndScriptJson));
export const GameStart = new ExecutableScript<{
  game: HexString;
  gameId: bigint;
  price: bigint;
}>(Script.fromJson(GameStartScriptJson));
export const GameWithdraw = new ExecutableScript<{
  game: HexString;
  gameId: bigint;
  epochParticipation: HexString;
  addressToClaim: Address;
}>(Script.fromJson(GameWithdrawScriptJson));
export const NewInterval = new ExecutableScript<{
  predict: HexString;
  newRecurrence: bigint;
}>(Script.fromJson(NewIntervalScriptJson));
export const NewOperator = new ExecutableScript<{
  predict: HexString;
  newOperatorAddress: Address;
}>(Script.fromJson(NewOperatorScriptJson));
export const Start = new ExecutableScript<{
  predict: HexString;
  price: bigint;
}>(Script.fromJson(StartScriptJson));
export const Withdraw = new ExecutableScript<{
  predict: HexString;
  epochParticipation: HexString;
  addressToClaim: Address;
}>(Script.fromJson(WithdrawScriptJson));
